### ISSUE TITLE
MemoryError: Delete operation for /dasdpartitions fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#113]
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://127.0.0.1:8001/plugins/ginger/dasdpartitions/dasdd'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}  

log captured:

[04/Jan/2016:09:47:28] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 176, in index
    'PUT': self.update}[method](*args, **kargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 153, in delete
    fn(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/dasdpartitions.py", line 89, in delete
    dasd_utils._delete_dasd_part(dev_name, part_num)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/dasd_utils.py", line 341, in _delete_dasd_part
    out, err = p2_out.communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 806, in communicate
    return self._communicate(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1388, in _communicate
    stdout = ''.join(stdout)
MemoryError

**Comment by sureshab** [comment]
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://127.0.0.1:8001/plugins/ginger/dasdpartitions/dasde'
Enter host password for user 'root':
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>


Wokd will be killed after the api

**Comment by harche** [comment]
I will be working on this issue

**Comment by sureshab** [comment]
delete a dasdpartition which doesn't exist--fails with 500

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://localhost:8001/plugins/ginger/dasdpartitions/invalid'
Enter host password for user 'root':
{
  "reason":"GINDASDPAR0002E: Error while getting block device information",
  "code":"500 Internal Server Error"
}

**Comment by pawankg** [comment]
Patch for this issue is sent for review.

**Comment by pawankg** [comment]
This issue is fixed in the upstream code so this can be closed.
