### ISSUE TITLE
nfs mount fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#166]
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"nfs","server":"","share":"","mount_point":""}' 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}  

log : 
[09/Jan/2016:19:33:26] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 353, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 285, in create
    name = create(*args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/filesystem.py", line 74, in create
    fs_utils.nfsmount(server, share, mount_point)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/fs_utils.py", line 301, in nfsmount
    raise OperationFailed("GINFS00018E", err)
  File "/usr/lib/python2.7/site-packages/wok/exception.py", line 33, in __init__
    for key, value in args.iteritems():
AttributeError: 'str' object has no attribute 'iteritems'

**Comment by sureshab** [comment]
with valid nfs server and invalid share & mount point
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"nfs","server":"9.152.151.103","share":"dummy","mount_point":"dummy"}' 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
} 

it took approximately 2 minutes

**Comment by sureshab** [comment]
mounting already mounted nfs file system - 

[root@zfwcec164 ~]# df -hT
Filesystem             Type      Size  Used Avail Use% Mounted on
/dev/dasda1            ext3       23G  3.2G   18G  16% /
devtmpfs               devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs                  tmpfs     1.9G  4.0K  1.9G   1% /dev/shm
tmpfs                  tmpfs     1.9G   26M  1.9G   2% /run
tmpfs                  tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/dasdc2            ext4      4.7G   20M  4.5G   1% /root/mount_dev
localhost:/var/ftp/nfs nfs4       23G  3.2G   18G  16% /root/new
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"nfs","server":"localhost","share":"/var/ftp/nfs","mount_point":"/root/new"}' 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}

**Comment by pkulkark** [comment]
I will be sending a patch for this
