### ISSUE TITLE
test cases using objectstore fail

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#213]
Unit test cases using objectstore instances fail

For Example:
[pkulkarni@localhost tests]$ ./run_tests.sh test_partitions

EEEEEEEE
ERROR: test_change_part_type (test_partitions.PartitionTests)
Traceback (most recent call last):
  File "test_partitions.py", line 33, in setUp
    self._objstore = ObjectStore(objstore_loc)
  File "/home/pkulkarni/git/ginger-for-patch/wok/src/wok/objectstore.py", line 102, in __init__
    self._init_db()
  File "/home/pkulkarni/git/ginger-for-patch/wok/src/wok/objectstore.py", line 105, in _init_db
    conn = self._get_conn()
  File "/home/pkulkarni/git/ginger-for-patch/wok/src/wok/objectstore.py", line 129, in _get_conn
    timeout=10)
OperationalError: unable to open database file

Other test cases failing with similar error:
test_physical_vol.py
test_vol_group.py
test_log_volume.py
test_swap.py

**Comment by danielhb** [comment]
The tests need to be executed with 'sudo' because the objstore file is created with root privileges.
