### ISSUE TITLE
Wokd service failing to start with latest repository

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#228]
After taking a fresh clone of ginger repository and installing it, wokd service is failing to start with following error:
[root@localhost ftp]# wokd
Plugin configuration file /etc/wok/plugins.d/gingers390x.conf doesn't exist.
Plugin configuration file /etc/wok/plugins.d/kimchi.conf doesn't exist.
Traceback (most recent call last):
  File "/bin/wokd", line 101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/bin/wokd", line 98, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 235, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 167, in __init__
    self._load_plugins(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 188, in _load_plugins
    plugin_app = import_class(plugin_class)(options)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/ginger.py", line 52, in __init__
    self.backup = Backup(self.model)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/control/backup.py", line 48, in __init__
    self.archives = Archives(model)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/control/backup.py", line 62, in __init__
    self.log_args.update({'description': ''})
AttributeError: 'Archives' object has no attribute 'log_args'

**Comment by danielhb** [comment]
Problem was solved
