### ISSUE TITLE
Administration tab fails to load

### ISSUE THREAD

**Issue by p2baron** [kimchi-project/ginger#28]
I've compiled Kimchi and Ginger from source on an Ubuntu 14.04 system.
Everything works fine except I'm unable to open the administration tab.

The following error show in the kimchi log file

    [17/Oct/2015:16:28:51] HTTP Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
        response.body = self.handler()
      File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/kimchi/root.py", line 92, in default
        return template.render(page, kwargs)
      File "/usr/lib/python2.7/dist-packages/kimchi/template.py", line 109, in render
        return render_cheetah_file(resource, data)
      File "/usr/lib/python2.7/dist-packages/kimchi/template.py", line 95, in render_cheetah_file
        return Template(file=filename, searchList=params).respond()
      File "_usr_share_kimchi_plugins_ginger_ui_pages_host_admin_html_tmpl.py", line 106, in respond
      File "/usr/lib/python2.7/gettext.py", line 484, in translation
        raise IOError(ENOENT, 'No translation file found for domain', domain)
    IOError: [Errno 2] No translation file found for domain: 'ginger'

The file  /etc/libuser.conf is present on my system.
Any pointers in how to solve this issue?

**Comment by danielhb** [comment]
I'll test it in a Ubuntu 14 VM to see if I can reproduce the issue.

What commands did you use to compile Ginger? We need to improve the source code docs .... the compile procedure after a clone is:

$ autogen.sh --system
$ make

**Comment by p2baron** [comment]
I used those commands and a "sudo make install"

**Comment by p2baron** [comment]
Discovered what the issue is.
It turned out that a language file is missing. 
Python looks for a translation file for the language in which the client operating system (or browser?) is configured. In my case that is Dutch. (I am from the Netherlands).
I've copied the contents from "/usr/share/kimchi/plugins/ginger/mo/en_US" to a new directory called "nl_NL".
After that I've modified the "ginger.mo" and set the language from "en_US" to "nl_NL"

Would be nice if Ginger/Kimchi switches to English when no matching translation file is found.

**Comment by pvital** [comment]
That's weird because Kimchi should set to en_US automatically when a language is not found.

@danielhb is it possible to move an issue from here to Kimchi? If not, @p2baron, please, open an issue on Kimchi project (https://github.com/kimchi-project/kimchi) describing the language problem. 

@alinefm FYI

**Comment by danielhb** [comment]
Before forwarding this bug to kimchi let me ask. @p2baron , this problem happened only with the Administration tab? Does it happened with other tabs such as Guests or Templates or other Kimchi tab? 

Just to make sure that the problem is indeed where @pvital says it is before forwarding the bug.

**Comment by p2baron** [comment]
It happened only on the administration tab.

**Comment by danielhb** [comment]
I'll talk with @alinefm about it to see if this is indeed a problem in Ginger or perhaps it is a bug in a new component (WoK) we've started to use.

**Comment by danielhb** [comment]
@p2baron can you try it out with the new release? You can find packages for Ubuntu here:

http://kimchi-project.github.io/wok/downloads/
http://kimchi-project.github.io/gingerbase/downloads/
http://kimchi-project.github.io/ginger/downloads/

**Comment by danielhb** [comment]
Let me know if you still having issues with the administration tab yet. Feel free to reopen this issue or create a new one

Thanks

**Comment by jarredkenny** [comment]
I am having this exact same issue on a fresh Centos 7 install. Even after only installing wok (before installing ginger-base and kimchi). I am using the rpms from the sites linked above.

```
[17/Dec/2016:13:04:10] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 130, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_settings_html_tmpl.py", line 105, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'
```
