### ISSUE TITLE
Format DASD large count of DASD from UI, hangs the browser, exception "[Errno 24] Too many open files"

### ISSUE THREAD

**Issue by harche** [kimchi-project/ginger#310]
After I enable approx 1470 devices(all ECKD devices on my system), started formatting all the storage devices.

Wok-error log has

```
[22/Feb/2016:16:43:20] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1887, in tick
    s, addr = self.socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 24] Too many open files
```

**Comment by harche** [comment]
This can be fixed by limiting the number DASD devices getting formatted concurrently.

**Comment by harche** [comment]
I will work on this issue.
