### ISSUE TITLE
Ginger tests failing after WoK change on nginx

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#374]
```
======================================================================
ERROR: setUpModule (test_authorization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/plugins/ginger/tests/test_authorization.py", line 42, in setUpModule
    test_server = run_server(host, port, ssl_port, test_mode=True, model=model)
  File "/home/danielhb/kimchi/wok_all_plugins/tests/utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 118, in _create_proxy_config
    dst = os.path.join(paths.sys_nginx_conf_dir, "wok.conf")
AttributeError: 'Paths' object has no attribute 'sys_nginx_conf_dir'

======================================================================
ERROR: setUpModule (test_tasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/plugins/ginger/tests/test_tasks.py", line 56, in setUpModule
    cherrypy_port=cherrypy_port, model=model)
  File "/home/danielhb/kimchi/wok_all_plugins/tests/utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 118, in _create_proxy_config
    dst = os.path.join(paths.sys_nginx_conf_dir, "wok.conf")
AttributeError: 'Paths' object has no attribute 'sys_nginx_conf_dir'

----------------------------------------------------------------------
```

@pvital said he will take a look into it

**Comment by danielhb** [comment]
Update: some Gingerbase Kimchi tests are failing too. Same error message.

I'll update the bug description.

**Comment by danielhb** [comment]
Scrap that

I'll open a bug on each plug-in

**Comment by danielhb** [comment]
Looking closely to the error message, the component is a WoK module:

  File "/home/danielhb/kimchi/wok_all_plugins/tests/utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 118, in _create_proxy_config
    dst = os.path.join(paths.sys_nginx_conf_dir, "wok.conf")

Instead of opening 2 new bugs, I'll open a WoK bug to investigate this. I believe a fix there will solve the problem on all plug-ins.
