### ISSUE TITLE
Fedora 24: Cannot create new volume group in 'Storage - Volume Groups' tab

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/ginger#398]
It's not possible to create new volume group, when I click 'Create physical volumes' (step 3), the button don't do anything.

<img width="844" alt="screen shot 2016-09-13 at 5 52 49 pm" src="https://cloud.githubusercontent.com/assets/6681745/18491100/3fa71760-79db-11e6-990c-62567e1bf77e.png">

**Comment by pvital** [comment]
@biancafc I guess you need add one more disk to your system to be able to create the new physical volume.

I had the same issue when testing on Ubuntu 16.04, but my system has two disks. The error I got was "GINPV00002E: Failed to create PV /dev/vdc."

![screenshot from 2016-09-14 10-24-08](https://cloud.githubusercontent.com/assets/699330/18513888/a6b88882-7a65-11e6-8fe2-dda2109344c6.png)

In wok-error.log I got the followinng error:

```
rc: 5 error: File descriptor 3 (/var/lib/wok/user-requests.data) leaked on pvcreate invocation. Parent PID 2546: python2
File descriptor 8 (/var/log/wok/wok-error.log) leaked on pvcreate invocation. Parent PID 2546: python2
File descriptor 60 (/var/log/wok/wok-access.log) leaked on pvcreate invocation. Parent PID 2546: python2
  Device /dev/vdc not found (or ignored by filtering).
 returned from cmd: pvcreate -f /dev/vdc
GINPV00008E: pvcreate command failed
GINPV00002E: Failed to create PV /dev/vdc.
Error in async_task eebaba7e-7a7e-11e6-9866-525400bb1df5 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wok/asynctask.py", line 107, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/dist-packages/wok/plugins/ginger/model/physical_vol.py", line 72, in _create_task
    {'name': pvname})
OperationFailed: GINPV00002E: Failed to create PV /dev/vdc.
```
