### ISSUE TITLE
UI is not updated after brigging an interface down/up

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#410]
![639f0d49f6ff289c](https://cloud.githubusercontent.com/assets/4921718/18523053/e379ebd0-7a88-11e6-9690-17a0d92337ec.jpg)

**Comment by biancafc** [comment]
Hello, 

I've tried to reproduce this bug in Fedora 24 and as the image shows below, when I try to disable the interface the UI is updating the status correctly:

![screen shot 2016-10-21 at 17 43 48](https://cloud.githubusercontent.com/assets/6681745/19609477/366b4a60-97b6-11e6-872e-4f9fcd2de9d7.png)

**Comment by alinefm** [comment]
Hi @biancafc 

I tested it again and I could not reproduce the issue anymore (commit 3ad0c117f8c1ff41f89d912e62da27f089fb94c2)

But while trying to get an iface up I got the following error:

```
[11/Nov/2016:13:05:20] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/wok/src/wok/control/base.py", line 144, in wrapper
    action_result = action_fn(*model_args)
  File "/root/wok/src/wok/plugins/ginger/model/interfaces.py", line 99, in activate
    InterfacesHelper().activate_iface(ifacename)
  File "/root/wok/src/wok/plugins/ginger/model/nw_interfaces_utils.py", line 160, in activate_iface
    carrier_val = car_file.readline().strip()
IOError: [Errno 22] Invalid argument

ERROR:cherrypy.error.38685392:[11/Nov/2016:13:05:20] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/wok/src/wok/control/base.py", line 144, in wrapper
    action_result = action_fn(*model_args)
  File "/root/wok/src/wok/plugins/ginger/model/interfaces.py", line 99, in activate
    InterfacesHelper().activate_iface(ifacename)
  File "/root/wok/src/wok/plugins/ginger/model/nw_interfaces_utils.py", line 160, in activate_iface
    carrier_val = car_file.readline().strip()
IOError: [Errno 22] Invalid argument
```

I am testing on a VM, so my ifaces are virtual but I think it should not be a problem.
I will open a separated bug to cover what I described above,

**Comment by alinefm** [comment]
Just forgot to mentioned that I tested on CentOS 7
