### ISSUE TITLE
make check fails at opensuse 42.1

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/ginger#411]
Output

```
linux-bdc7:~/WOK/src/wok/plugins/ginger # make check
Making check in po
make[1]: Entering directory '/root/WOK/src/wok/plugins/ginger/po'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/root/WOK/src/wok/plugins/ginger/po'
Making check in control
make[1]: Entering directory '/root/WOK/src/wok/plugins/ginger/control'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/root/WOK/src/wok/plugins/ginger/control'
Making check in model
make[1]: Entering directory '/root/WOK/src/wok/plugins/ginger/model'
make  check-am
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/model'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/model'
make[1]: Leaving directory '/root/WOK/src/wok/plugins/ginger/model'
Making check in ui
make[1]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui'
Making check in config
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/config'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/config'
Making check in css
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/css'
Making check in base
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/css/base'
Making check in images
make[4]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/css/base/images'
make[4]: Nothing to be done for 'check'.
make[4]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/css/base/images'
make[4]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/css/base'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/css/base'
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/css/base'
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/css'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/css'
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/css'
Making check in js
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/js'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/js'
Making check in pages
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages'
Making check in help
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help'
Making check in en_US
make[4]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help/en_US'
make[4]: Nothing to be done for 'check'.
make[4]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help/en_US'
Making check in pt_BR
make[4]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help/pt_BR'
make[4]: Nothing to be done for 'check'.
make[4]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help/pt_BR'
Making check in zh_CN
make[4]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help/zh_CN'
make[4]: Nothing to be done for 'check'.
make[4]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help/zh_CN'
make[4]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help'
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages/help'
Making check in tabs
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages/tabs'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages/tabs'
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/pages'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages'
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/pages'
Making check in images
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui/images'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui/images'
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/ui'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui'
make[1]: Leaving directory '/root/WOK/src/wok/plugins/ginger/ui'
Making check in contrib
make[1]: Entering directory '/root/WOK/src/wok/plugins/ginger/contrib'
make  check-recursive
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/contrib'
Making check in DEBIAN
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/contrib/DEBIAN'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/contrib/DEBIAN'
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/contrib'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/contrib'
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/contrib'
make[1]: Leaving directory '/root/WOK/src/wok/plugins/ginger/contrib'
Making check in tests
make[1]: Entering directory '/root/WOK/src/wok/plugins/ginger/tests'
make  check-am
make[2]: Entering directory '/root/WOK/src/wok/plugins/ginger/tests'
make  check-local
make[3]: Entering directory '/root/WOK/src/wok/plugins/ginger/tests'
./run_tests.sh
....Cannot upgrade objectstore schema: no such table: objects
Error while upgrading objectstore data: no such table: objects
KCHUTILS0006E: KCHUTILS0006E
Failed to import plugin plugins.kimchi.Kimchi, error: KCHUTILS0006E: KCHUTILS0006E
[14/Sep/2016:14:33:27] ENGINE Bus STARTING
[14/Sep/2016:14:33:27] ENGINE Started monitor thread 'Autoreloader'.
[14/Sep/2016:14:33:27] ENGINE Serving on http://127.0.0.1:53404
[14/Sep/2016:14:33:27] ENGINE Bus STARTED
[14/Sep/2016:14:33:27] ENGINE Started monitor thread 'Session cleanup'.
127.0.0.1 - - [14/Sep/2016:14:33:27] "GET /plugins/ginger/capabilities HTTP/1.0" 200 1266 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:29] "GET /plugins/ginger/firmware HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:31] "GET /plugins/ginger/backup HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:33] "GET /plugins/ginger/backup/archives HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:35] "GET /plugins/ginger/ibm_sep HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:37] "GET /plugins/ginger/network HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:38] "GET /plugins/ginger/network/interfaces HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:41] "GET /plugins/ginger/network/cfginterfaces HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:42] "GET /plugins/ginger/powerprofiles HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:44] "GET /plugins/ginger/san_adapters HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:46] "GET /plugins/ginger/sensors HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:48] "GET /plugins/ginger/users HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:49] "GET /plugins/ginger/dasddevs HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:51] "GET /plugins/ginger/dasdpartitions HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:53] "GET /plugins/ginger/partitions HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:55] "GET /plugins/ginger/filesystems HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:57] "GET /plugins/ginger/lvs HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:33:59] "GET /plugins/ginger/pvs HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:34:00] "GET /plugins/ginger/storagedevs HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:34:02] "GET /plugins/ginger/swaps HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:34:04] "GET /plugins/ginger/sysmodules HTTP/1.0" 401 1125 "" ""
WOKAUTH0001E: Authentication failed for user 'root'. [Error code: 7]
127.0.0.1 - - [14/Sep/2016:14:34:06] "GET /plugins/ginger/vgs HTTP/1.0" 401 1125 "" ""
.[14/Sep/2016:14:34:06] ENGINE Bus STOPPING
[14/Sep/2016:14:34:06] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 53404)) shut down
[14/Sep/2016:14:34:06] ENGINE Stopped thread 'Session cleanup'.
[14/Sep/2016:14:34:06] ENGINE Stopped thread 'Autoreloader'.
[14/Sep/2016:14:34:06] ENGINE Bus STOPPED
[14/Sep/2016:14:34:06] ENGINE Bus EXITING
[14/Sep/2016:14:34:06] ENGINE Bus EXITED
[14/Sep/2016:14:34:06] ENGINE Waiting for child threads to terminate...
..Unable to get mac address of dummyiface, error 0.
GINNET0081E: Unable to create a new network script file for the interface dummyiface.
..E....GINNET0092E: invalid_mac is not a valid mac address.
.GINNET0024E: Basic information of interface is missing.
.........rc: 1 error: mount: /testfile is already mounted
 returned from cmd: /bin/mount /testfile /test
Mounting block device failed
GINFS00007E: Failed to mount the filesystem
GINFS00007E: Failed to mount the filesystem
...GINFS00017E: Invalid type needs to be either local or nfs
.GINFS00010E: Require mount point to mount a filesystem
.GINFS00014E: required server ip addr
.GINFS00015E: required remote share location
.GINFS00016E: required type as local or nfs
.
...
.GINFW0001E: Cannot update system firmware while running VMs.
.FW update: System will reboot to flash the firmware.
.FW update: System will reboot to flash the firmware.
.........Bring up an interface test_eth0
Time-out has happened upon execution of 'ip link set <interface> up', hence behavior of activating an interface may not as expected.
Activating an interface test_eth0
GINNET0091E: Run time information is not available for the interface on 'test_eth0'. Activation of the interface on 'test_eth0' went wrong.
.Bring up an interface test_eth0
GINNET0059E: Unable to bring up the interface 'test_eth0', 'Unable to activate'.
.Deactivating an interface test_eth0
Connection successfully deactivated for the interface test_eth0
Bringing down an interface test_eth0
Time-out has happened upon execution of 'ip link set <interface> down', hence behavior of activating an interface may not as expected.
.Deactivating an interface test_eth0
GINNET0017E: Unable to deactivate the interface on 'test_eth0', 'Unable to deactivate'.
..GINNET0076E: Interface any_iface_name loaded with driver unknown does not support SR-IOV.
.GINNET0079E: SR-IOV enablement failed: num_vfs must be an integer.
..GINNET0088E: Error: openib.conf file does not exist in the host. Unable to set SR-IOV boot script.
.GINNET0084E: SR-IOV is already configured in interface iface1 with 8 virtual functions.
.GINNET0083E: Unable to set 16 virtual functions for interface iface1. Maximum allowed in the firmware is 8.
....GINNET0077E: SR-IOV action of mlx5 module requires 'num_vfs' argument.
.GINNET0078E: SR-IOV enablement failed: required files under /sys directory not found.
.GINNET0082E: SR-IOV is not enabled in the firmware of the interface iface1.
......GINNET0093E: SR-IOV is already disabled (no virtual functions enabled) in interface iface1.
..........GINLV00002E: Required size parameter
.GINLV00001E: Required vg_name parameter
....rc: 1 error: clnt_create: RPC: Port mapper failure - Unable to receive: errno 111 (Connection refused)
 returned from cmd: showmount --no-headers --exports abc
GINNFS00002E: Invalid server or no NFS exports found on server.
.GINOVS00006E: Unable to create bond with less than two interfaces.
....Error executing ovs-vsctl add-port: ovs-vsctl: cannot create a port named iface because a port named iface already exists on bridge bridge 
GINOVS00005E: Error adding port iface in bridge bridge. Port already exists.
.......GINOVS00003E: Error creating OVS bridge bridge. OVS bridge already exists.
.GINOVS00001E: Error executing OVS command. Please check if 'openvswitch' service is running.
.OVS bridge bridge created.
.OVS Bridge bridge deleted.
.......GINPART00008E: Required parameter device name
.GINPART00009E: Required parameter partition size
....: Project-Id-Version: kimchi 0.1
Report-Msgid-Bugs-To: 
POT-Creation-Date: 2016-06-24 09:46-0300
PO-Revision-Date: 2013-07-11 17:32-0400
Last-Translator: Crístian Viana <vianac@linux.vnet.ibm.com>
Language-Team: English
Language: en_US
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Generated-By: pygettext.py 1.5
Plural-Forms: nplurals=2; plural=(n != 1);

GINPART00014E: Partition /a/invalid/partition not found.
.GINPV00001E: Required pv_name parameter.
.....GINPV00011E: Unable to find device fake_dev .
.GINPV00007E: Unable to get information of device fake_dev, error: 
.GINPV00010E: Remove failed: device fake_dev not found.
.GINPV00009E: Remove failed: error: 
.................Deleting the existing rule -a always,exit -F arch=b32 -F arch=b64 -S init_module,delete_module,finit_module -F key=abc99
The rule has been modified successfully.
..GINSEL00001E: Unable to get System Event Log information for server serverpresent. IPMI Command error error. rc = 1
.GINSEL00001E: Unable to get System Event Log information for server serverpresent. IPMI Command error error. rc = 1
.GINSEL00004E: Unable to delete System Event Log 1 for server serverpresent. IPMI Command error error. rc =1
..GINSEL00005E: Cannot process System Event Log entry 5 | 08/08/2016 | 11:46:0Event #0x5dabc | Asserted
..GINSEL00003E: System Event Log 1 is not present in System Event Log information for server serverpresent
...GINSE00003E: Error while getting the status of server with name abc and IP address or Host Name 127.0.0.1. Please check the server details and retry the operation.
....GINSE00003E: Error while getting the status of server with name abc and IP address or Host Name 127.0.0.1. Please check the server details and retry the operation.
..GINSE00003E: Error while getting the status of server with name abc and IP address or Host Name 127.0.0.1. Please check the server details and retry the operation.
...GINSEL00002E: Unable to get details of server server1
.GINSDR00003E: invalidqueryparam is not a valid sensor type
...GINSDR00001E: Unable to get SDR information for server serverpresent. IPMI Command error error , rc = 1
..GINSDR00003E: invalidqueryparam is not a valid sensor type
.GINSERV00002E: Service name unknown.service not found.
.............................GINSP00001E: File location required for creating a swap device.
.GINSP00003E: Size is mandatory while creating file type swap device.
.GINSP00002E: Type required for creating a swap device.
.GINSP00004E: Incorrect swap type, only 'device' and 'file' are allowed.
..GINSP00018E: Single swap device fake_device_name not found.
.GINSP00019E: Unable to get single swap device info: directory /proc/swaps not found.
.GINSP00015E: Unable to get single swap device info. 
..GINSYSMOD00006E: Module fake_test_kernel_module is already loaded in the kernel.
.....Kernel module fake_test_kernel_module loaded.
.Kernel module fake_test_kernel_module loaded.
.Kernel module fake_test_kernel_module unloaded.
.....Cannot upgrade objectstore schema: no such table: objects
Error while upgrading objectstore data: no such table: objects
KCHUTILS0006E: KCHUTILS0006E
Failed to import plugin plugins.kimchi.Kimchi, error: KCHUTILS0006E: KCHUTILS0006E
[14/Sep/2016:14:34:32] ENGINE Bus STARTING
[14/Sep/2016:14:34:32] ENGINE Started monitor thread 'Session cleanup'.
[14/Sep/2016:14:34:32] ENGINE Started monitor thread 'Autoreloader'.
[14/Sep/2016:14:34:32] ENGINE Serving on http://127.0.0.1:53404
[14/Sep/2016:14:34:32] ENGINE Bus STARTED
127.0.0.1 - - [14/Sep/2016:14:34:32] "GET /plugins/ginger/tasks?status=running&target_uri=%5E%2Fplugins%2Fginger%2Ftasks%2F%2A HTTP/1.0" 200 527 "" ""
127.0.0.1 - - [14/Sep/2016:14:34:32] "GET /plugins/ginger/tasks HTTP/1.0" 200 1709 "" ""
127.0.0.1 - - [14/Sep/2016:14:34:32] "GET /plugins/ginger/tasks/7f5e8520-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 161 "" ""
Waiting task 7f5e8520-7aa1-11e6-85e0-525400b5322c, message: The request is being processing.
Error in async_task 7f5e8520-7aa1-11e6-85e0-525400b5322c 
Traceback (most recent call last):
  File "/root/WOK/src/wok/asynctask.py", line 74, in _run_helper
    self.fn(cb, opaque)
  File "/root/WOK/src/wok/plugins/ginger/tests/test_tasks.py", line 69, in _except_op
    raise Exception("Oops, this is an exception handle test."
Exception: Oops, this is an exception handle test. You can ignore it safely

127.0.0.1 - - [14/Sep/2016:14:34:33] "GET /plugins/ginger/tasks/7f5e8520-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 192 "" ""
127.0.0.1 - - [14/Sep/2016:14:34:33] "GET /plugins/ginger/tasks/7f5e8520-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 192 "" ""
127.0.0.1 - - [14/Sep/2016:14:34:33] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:34] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:35] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:36] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:37] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:38] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:39] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:40] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:41] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
127.0.0.1 - - [14/Sep/2016:14:34:42] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
Waiting task 7f5e901a-7aa1-11e6-85e0-525400b5322c, message: in progress
Timeout while process long-run task, try to increase timeout value.
127.0.0.1 - - [14/Sep/2016:14:34:43] "GET /plugins/ginger/tasks/7f5e901a-7aa1-11e6-85e0-525400b5322c HTTP/1.0" 200 140 "" ""
.[14/Sep/2016:14:34:43] ENGINE Bus STOPPING
[14/Sep/2016:14:34:43] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 53404)) shut down
[14/Sep/2016:14:34:43] ENGINE Stopped thread 'Session cleanup'.
[14/Sep/2016:14:34:43] ENGINE Stopped thread 'Autoreloader'.
[14/Sep/2016:14:34:43] ENGINE Bus STOPPED
[14/Sep/2016:14:34:43] ENGINE Bus EXITING
[14/Sep/2016:14:34:43] ENGINE Bus EXITED
GINUSER0003E: User password is a required string.
.GINUSER0002E: User name is a required string.
.GINUSER0024E: Failed to change password for user 'user1', error: 'fail'.
.[14/Sep/2016:14:34:43] ENGINE Waiting for child threads to terminate...
.GINUSER0011E: User 'user1' does not exist.
.GINUSER0018E: Group name 'dummy_group' is already in use'.
.GINUSER0014E: There was a problem while creating group ''. Group name is an empty string.
.GINUSER0014E: There was a problem while creating group '12'. Group name is an empty string.
.GINUSER0014E: There was a problem while creating group 'dummy_group'. Group name is an empty string.
..GINUSER0009E: There was a problem while creating user 'dummy_user', error: user name is empty.
.GINUSER0008E: User/Login 'dummy_user' already in use.
..GINUSER0009E: There was a problem while creating user 'dummy_user', error: user name is empty.
.GINUSER0012E: There was a problem while deleting group ''. Group name is an empty string.
.GINUSER0012E: There was a problem while deleting group '12'. Group name is an empty string.
..GINUSER0017E: Deletion is not supported for group found in '/etc/sudoers' file. Group: dummy_group
...GINUSER0010E: There was a problem while deleting user '', error: user name is empty.
.GINUSER0010E: There was a problem while deleting user 'dummy_user', error: user name is empty.
.GINUSER0010E: There was a problem while deleting user '12', error: user name is empty.
.GINUSER0011E: User 'dummy_user' does not exist.
..GINUSER0016E: Deletion is not supported for users found in '/etc/sudoers' file. User: dummy_user
.GINUSER0013E: Failed to remove user 'dummy_user' from sudoers list
.......GINUSER0023E: There was a problem while fetching user profile, see log for details
.GINUSER0002E: User name is a required string.
.GINUSER0011E: User 'user1' does not exist.
..GINUSER0011E: User 'user1' does not exist.
.GINUSER0011E: User 'user1' does not exist.
.GINUSER0006E: Could not add user 'user1' to kvm group.
..GINUSER0007E: Could not add user 'user1' to sudoers list, error: 'fail'.
....GINVG00013E: Required vg_name parameter
.GINVG00014E: Required pv_paths parameter
.....GINLVM0001E: Error parsing output of 'lvm version' command: 'NoneType' object has no attribute 'group'
..
======================================================================
ERROR: test_get_basic_info (test_cfginterfaces.CfgInterfacesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/WOK/src/wok/plugins/ginger/tests/test_cfginterfaces.py", line 38, in test_get_basic_info
    self.assertEquals('testdevice', ethinfo['BASIC_INFO']['DEVICE'])
KeyError: 'DEVICE'

----------------------------------------------------------------------
Ran 268 tests in 80.983s

FAILED (errors=1)
Makefile:474: recipe for target 'check-local' failed
make[3]: *** [check-local] Error 1
make[3]: Leaving directory '/root/WOK/src/wok/plugins/ginger/tests'
Makefile:351: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/root/WOK/src/wok/plugins/ginger/tests'
Makefile:353: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/root/WOK/src/wok/plugins/ginger/tests'
Makefile:541: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by danielhb** [comment]
same error happened on opensuse 42.2
