### ISSUE TITLE
Plugin Ginger could not be loaded

### ISSUE THREAD

**Issue by GerhardK90** [kimchi-project/ginger#443]
Hello, 
unfortunately my ginger plugin is not loading. 
I am using WOK, Gingerbase and Kimchi 2.2.0-0 and tried to install ginger from 
here http://kimchi-project.github.io/ginger/ which is (2.3.0, is that a problem?)

Here is my wok-error.log
WOKAUTH0002E: You are not authorized to access Kimchi
[20/Oct/2016:00:52:57] ENGINE Caught signal SIGTERM.
[20/Oct/2016:00:52:57] ENGINE Bus STOPPING
[20/Oct/2016:00:52:58] ENGINE Caught signal SIGTERM.
[20/Oct/2016:00:52:58] ENGINE Bus STOPPING
[20/Oct/2016:00:52:58] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) already shut down
[20/Oct/2016:00:52:58] ENGINE Stopped thread 'Session cleanup'.
[20/Oct/2016:00:52:58] ENGINE Bus STOPPED
[19/Oct/2016:00:52:58] ENGINE Bus EXITING
[20/Oct/2016:00:52:59] ENGINE Bus EXITED
[20/Oct/2016:00:52:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) shut down
[20/Oct/2016:00:52:59] ENGINE No thread running for Session cleanup.
[20/Oct/2016:00:52:59] ENGINE Bus STOPPED
[20/Oct/2016:00:52:59] ENGINE Bus EXITING
[20/Oct/2016:00:52:59] ENGINE Bus EXITED
[20/Oct/2016:00:52:59] ENGINE Waiting for child threads to terminate...
**Failed to import plugin plugins.ginger.Ginger, error: Class plugins.ginger.Ginger can not be imported, error: cannot import name get_all_model_instances**

*** Kimchi: Running feature tests ***
Service Libvirtd running ...: True
Cannot find '' in path: No such file or directory
NFS Target Probe support ...: False
Fibre Channel Host support .: True
Kernel VFIO support ........: True
Network Manager running ....: False
Memory Hotplug support .....: False
*** Kimchi: Feature tests completed ***

*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Loading AptUpdate features.
System Update Tool ...: True
Repo Management Tool .: deb
*** Ginger Base: Capabilities tests completed ***
[20/Oct/2016:00:53:14] ENGINE Listening for SIGHUP.
[20/Oct/2016:00:53:14] ENGINE Listening for SIGTERM.
[20/Oct/2016:00:53:14] ENGINE Listening for SIGUSR1.
[20/Oct/2016:00:53:14] ENGINE Bus STARTING
[20/Oct/2016:00:53:15] ENGINE Serving on http://127.0.0.1:8010

*** Kimchi: Running dependable feature tests ***
[20/Oct/2016:00:53:15] HTTP Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/cherrypy/cprequest.py", line 670, in respond
response.body = self.handler()
File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call_
self.body = self.oldhandler(args, *kwargs)
File "/usr/lib/python2.7/dist-packages/cherrypy/cpdispatch.py", line 61, in __call_
return self.callable(self.args, *self.kwargs)
File "/usr/lib/python2.7/dist-packages/cherrypy/_cptools.py", line 175, in handle_func
handled = self.callable(args, *self._merged_args(kwargs))
TypeError: staticfile() got multiple values for keyword argument 'filename'

QEMU stream support .......: True
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[20/Oct/2016:00:53:16] ENGINE Bus STARTED
[20/Oct/2016:00:53:18] ENGINE Started monitor thread 'Session cleanup'.
WOKAUTH0002E: You are not authorized to access Kimchi
WOKAUTH0002E: You are not authorized to access Kimchi
WOKAUTH0002E: You are not authorized to access Kimchi

Thank you for your help!!

**Comment by danielhb** [comment]
Hi, sorry for the delay in answering

The problem is that Ginger 2.3.0 requires WoK 2.3.0 and Gingerbase 2.2.0. Running an old version of both WoK and Gingerbase is causing this issue.

**Comment by GerhardK90** [comment]
Hello danielhb,
thank you for your reply. 
Do you mean that Ginger 2.3.0 needs Gingerbase 2.2.0 and WoK 2.3.0 in particular or is Gingerbase 2.2.1-0 also fine? Because I upgraded some days ago but still got the same error
![image](https://cloud.githubusercontent.com/assets/3868214/19732284/a0840930-9ba0-11e6-8bf9-1717039582c6.png)

**Comment by danielhb** [comment]
You'll want to use the latest versions of both WoK and Gingerbase. You can see them here:

http://kimchi-project.github.io/ginger/downloads/

If you're still experiencing the error, let me know which linux distro are you using and the error log. One thing to note is that if you upgraded one of WoK components you should need to do a 'systemctl daemon-reload'  to reload the wokd daemon with the latest files.
