### ISSUE TITLE
IOError: [Errno 22] Invalid argument when try to bring an interface up

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/ginger#469]
Tested in CentOS 7.

```
[11/Nov/2016:13:05:20] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/wok/src/wok/control/base.py", line 144, in wrapper
    action_result = action_fn(*model_args)
  File "/root/wok/src/wok/plugins/ginger/model/interfaces.py", line 99, in activate
    InterfacesHelper().activate_iface(ifacename)
  File "/root/wok/src/wok/plugins/ginger/model/nw_interfaces_utils.py", line 160, in activate_iface
    carrier_val = car_file.readline().strip()
IOError: [Errno 22] Invalid argument

ERROR:cherrypy.error.38685392:[11/Nov/2016:13:05:20] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/wok/src/wok/control/base.py", line 144, in wrapper
    action_result = action_fn(*model_args)
  File "/root/wok/src/wok/plugins/ginger/model/interfaces.py", line 99, in activate
    InterfacesHelper().activate_iface(ifacename)
  File "/root/wok/src/wok/plugins/ginger/model/nw_interfaces_utils.py", line 160, in activate_iface
    carrier_val = car_file.readline().strip()
IOError: [Errno 22] Invalid argument
```

**Comment by ramonmedeiros** [comment]
Did not reproduced the issue. Steps:

1) Go to Host->Network
2) Put interface down
3) Put interface up

Running ok

CentOS Linux release 7.2.1511 (Core) 
Running on master
```
INFO:cherrypy.access.30819408:192.168.124.1 - - [18/Nov/2016:21:22:38] "GET /notifications HTTP/1.0" 200 2 "https://192.168.124.190:8001/" "Mozilla/5.0 (X11; FreeBSD amd64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
Deactivating an interface eth1
INFO:cherrypy.error:Deactivating an interface eth1
Bringing down an interface eth1
INFO:cherrypy.error:Bringing down an interface eth1
Successfully brought down the interface eth1
INFO:cherrypy.error:Successfully brought down the 
```

**Comment by biancafc** [comment]
Hello, 

Please try to reproduce this error using a bond interface.

**Comment by ramonmedeiros** [comment]
Just tested with Bond.

Setup:
Centos 7.2
Two interfaces (eth1 and eth0)
Created a Bond on eth0, wok log:

Bring up an interface bond
INFO:cherrypy.error:Bring up an interface bond
Activating an interface bond
INFO:cherrypy.error:Activating an interface bond
Connection successfully activated for the interface bond
INFO:cherrypy.error:Connection successfully activated for the interface bond
INFO:wok_request_logger:{"info": {"status": 200, "zone": "EST", "ip": "192.168.124.1", "app": "/plugins/ginger", "req": "POST", "user": "root", "time": "09:43:55", "date": "2016-11-21"}, "message": {"code": "GINNET0005L", "params": {"ident": "bond"}}, "id": "fc934e13-a8c6-427a-82f8-36b96234d49d", "error": null}

**Comment by biancafc** [comment]
I've tried on Fedora 24:

Setup:
Two interfaces (ens33 and ens37)
Created a Bond on ens33, wok log when I tried to bring interface up:

```
rc: 1 error: Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
./network-functions: line 528: echo: write error: Operation not permitted
./network-functions: line 528: echo: write error: Operation not permitted
Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
./network-functions: line 528: echo: write error: Operation not permitted
./network-functions: line 528: echo: write error: Operation not permitted
 returned from cmd: ifup b1
ERROR:cherrypy.error:rc: 1 error: Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
./network-functions: line 528: echo: write error: Operation not permitted
./network-functions: line 528: echo: write error: Operation not permitted
Could not load file '/etc/sysconfig/network-scripts/ifcfg-b1'
./network-functions: line 528: echo: write error: Operation not permitted
./network-functions: line 528: echo: write error: Operation not permitted
 returned from cmd: ifup b1 
```

It's not the same message as the original but I'm pretty sure is the same reason (failes to open/edit configuration file)

Also got a error message in the UI:
Failed to bring up the interface b1. GINNET0094E: Activation of vlan/bond interface 'b1' failed. Please refresh and try again.

**Comment by ramonmedeiros** [comment]
Just found out that this error happens due Network Manager. We have two ways:

1) Ask user to disable NM (will work)

2) Reload NetworkManager, as asked here: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Network_Bonding_Using_the_Command_Line_Interface.html

**Comment by ramonmedeiros** [comment]
Tried to make BOND up with NetworkManager, but no success. Here is the Fedora 24 guide:

https://docs.fedoraproject.org/en-US/Fedora/24/pdf/Networking_Guide/Fedora-24-Networking_Guide-en-US.pdf

**Comment by ramonmedeiros** [comment]
After a lot of tests, just found out what is needed. Just follow the RFC at mailing list:

https://groups.google.com/forum/#!topic/ginger-dev-list/L_UEiaVuuhw
