### ISSUE TITLE
Some unit tests are 'unstable', failing randomly

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#48]
A couple of unit tests are failing at random. If you run the run_tests.sh script again after the failure there is a chance that it won't fail again. This was tested in a x86_64 running Fedora 22. 

One of the tests that are acting randomly:

```
 ======================================================================
FAIL: test_create_vg (test_vol_group.VolumeGroupsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/wok/kimchi/src/wok/plugins/ginger/tests/test_vol_group.py", line 58, in test_create_vg
    mock_create_vg.assert_called_with(vgname, pvpaths)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _create_vg('testvg', ['/dev/sdb1'])
Not called

----------------------------------------------------------------------
```

I'll update this issue if I see the other test failing again.

**Comment by danielhb** [comment]
A fix was sent to the ML. The problem was that these 3 tests weren't waiting for the async tasks to finish their job before asserting the results.

**Comment by danielhb** [comment]
Issue fixed in master branch
