### ISSUE TITLE
make check fails on master branch

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#485]
======================================================================
ERROR: setUpModule (test_authorization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/wok/src/wok/plugins/ginger/tests/test_authorization.py", line 36, in setUpModule
    test_server = run_server(test_mode=True, model=model)
  File "/root/wok/tests/utils.py", line 103, in run_server
    s = wok.server.Server(args)
  File "/root/wok/src/wok/server.py", line 65, in __init__
    check_proxy_config()
  File "/root/src/wok/proxy.py", line 43, in check_proxy_config
    dirs = [paths.sys_nginx_conf_dir, paths.sys_conf_dir]
AttributeError: 'Paths' object has no attribute 'sys_conf_dir'

======================================================================
ERROR: setUpModule (test_tasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/wok/src/wok/plugins/ginger/tests/test_tasks.py", line 46, in setUpModule
    test_server = run_server(test_mode=True, model=model)
  File "/root/wok/tests/utils.py", line 103, in run_server
    s = wok.server.Server(args)
  File "/root/wok/src/wok/server.py", line 65, in __init__
    check_proxy_config()
  File "/root/wok/src/wok/proxy.py", line 43, in check_proxy_config
    dirs = [paths.sys_nginx_conf_dir, paths.sys_conf_dir]
AttributeError: 'Paths' object has no attribute 'sys_conf_dir'

----------------------------------------------------------------------
Ran 294 tests in 28.537s

FAILED (errors=2)

**Comment by danielhb** [comment]
It works for me here. Try to get latest WoK and Gingerbase, then run ./build-all.sh script in WoK. If the problem still occurs then we need to investigate if there is something else in your env.

**Comment by danielhb** [comment]
Let me know if the issue happens again. Closing for now
