### ISSUE TITLE
Unit tests failing in Ubuntu

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#50]
After a handful of new features entering upstream (and a lot more to come) the unit tests started to fail for Ubuntu due to the development being made considering only RPM (Fedora) distros

This issue will be used to track which unit tests are failing. I'll be actively working to try to close the gap between Ubuntu and Fedora, but any help is of course appreciated. 

Current score for unit tests in Ubuntu 15.10:

```
======================================================================
ERROR: test_create_user (test_user_model.UserModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_user_model.py", line 51, in test_create_user
    users_model.create(params)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 185, in create
    gid = get_group_gid(groupname)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 53, in get_group_gid
    adm = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
ERROR: test_creating_existing_user_fails (test_user_model.UserModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_user_model.py", line 76, in test_creating_existing_user_fails
    users_model.create(params)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 185, in create
    gid = get_group_gid(groupname)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 53, in get_group_gid
    adm = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
ERROR: test_create_existing_user_fails (test_libuser.UserAdmTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_libuser.py", line 64, in test_create_existing_user_fails
    users.create_user(user, passwd)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 122, in create_user
    adm = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
ERROR: test_create_group (test_libuser.UserAdmTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_libuser.py", line 76, in test_create_group
    groups = users.get_groups()
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 38, in get_groups
    adm = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
ERROR: test_create_user (test_libuser.UserAdmTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_libuser.py", line 47, in test_create_user
    users.create_user(user, passwd)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 122, in create_user
    adm = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
ERROR: test_get_users_list (test_libuser.UserAdmTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_libuser.py", line 36, in test_get_users_list
    all_users = users.get_users(exclude_system_users=False)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 105, in get_users
    admin = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
ERROR: test_list_existing_groups (test_libuser.UserAdmTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_libuser.py", line 71, in test_list_existing_groups
    groups = users.get_groups()
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/models/users.py", line 38, in get_groups
    adm = libuser.admin()
SystemError: could not open configuration file `/etc/libuser.conf': No such file or directory

======================================================================
FAIL: test_format_part (test_partitions.PartitionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_partitions.py", line 87, in test_format_part
    mock_format_part.assert_called_with(fstype, '/dev/' + name)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _makefs('ext4', '/dev/sdb1')
Not called

======================================================================
FAIL: test_create_vg (test_vol_group.VolumeGroupsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_vol_group.py", line 58, in test_create_vg
    mock_create_vg.assert_called_with(vgname, pvpaths)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _create_vg('testvg', ['/dev/sdb1'])
Not called

======================================================================
FAIL: test_create_lv (test_log_volume.LogicalVolumesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_log_volume.py", line 58, in test_create_lv
    mock_create_lv.assert_called_with(vgname, size)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _create_lv('testvg', '10M')
Not called

----------------------------------------------------------------------
Ran 68 tests in 14.721s

FAILED (failures=3, errors=7)

```

**Comment by danielhb** [comment]
Considering the workaround fix for libuser described in https://github.com/kimchi-project/ginger/issues/22 , we're now standing at:

```
======================================================================
FAIL: test_format_part (test_partitions.PartitionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_partitions.py", line 87, in test_format_part
    mock_format_part.assert_called_with(fstype, '/dev/' + name)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _makefs('ext4', '/dev/sdb1')
Not called

======================================================================
FAIL: test_create_vg (test_vol_group.VolumeGroupsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_vol_group.py", line 58, in test_create_vg
    mock_create_vg.assert_called_with(vgname, pvpaths)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _create_vg('testvg', ['/dev/sdb1'])
Not called

======================================================================
FAIL: test_create_lv (test_log_volume.LogicalVolumesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/danielhb/kimchi/src/wok/plugins/ginger/tests/test_log_volume.py", line 58, in test_create_lv
    mock_create_lv.assert_called_with(vgname, size)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 334, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 925, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: _create_lv('testvg', '10M')
Not called

----------------------------------------------------------------------
Ran 68 tests in 16.224s

FAILED (failures=3)
rc: 5 error: File descriptor 45 (/dev/null) leaked on lvcreate invocation. Parent PID 9944: python
File descriptor 46 (/dev/null) leaked on lvcreate invocation. Parent PID 9944: python
File descriptor 47 (/dev/null) leaked on lvcreate invocation. Parent PID 9944: python
File descriptor 48 (/dev/null) leaked on lvcreate invocation. Parent PID 9944: python
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
  Volume group "testvg" not found
 returned from cmd: lvcreate testvg -L 10M

```

**Comment by danielhb** [comment]
A fix was sent to the ML. The problem was that these 3 tests weren't waiting for the async tasks to finish their job before asserting the results.

This problem is the same as described in https://github.com/kimchi-project/ginger/issues/48 .

**Comment by danielhb** [comment]
Issue fixed in master branch
