### ISSUE TITLE
Create physical volume fails on dasd/iscsi/fclun partitions

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#530]
Install wok, gingerbase, ginger, gingers390x.
Go to Host -> Storage -> Volume Group -> Add.
Create new in pv on partition of dasd-eckd/iscsi/fclun.

Error: GGBDISK00003E: GGBDISK00003E

Log:

Error in async_task 8afddc08-e795-11e6-a66d-0200000bf73c
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wok/asynctask.py", line 107, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/model/physical_vol.py", line 67, in _create_task
    part.change_type(part_name, type)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/model/diskparts.py", line 122, in change_type
    utils.change_part_type(name, type)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/model/utils.py", line 218, in change_part_type
    majmin = _get_dev_major_min(devname)
  File "/usr/lib/python2.7/site-packages/wok/plugins/gingerbase/disks.py", line 79, in _get_dev_major_min
    raise NotFoundError("GGBDISK00003E", {'device': name})
NotFoundError: GGBDISK00003E: GGBDISK00003E

**Comment by sureshab** [comment]
i will be working on this issue
