### ISSUE TITLE
Error 500 getting firmware level when lsmcode is not installed on Power

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/ginger#60]
sudo curl -u root -H "Content-Type: application/json" -H "Accept: application/json" "http://localhost:8010/plugins/ginger/firmware" -X GET -d '{}'

[09/Dec/2015:13:51:02] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 169, in index
    self.lookup()
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 145, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/firmware.py", line 54, in lookup
    if output.split()[5] != 'Product':
IndexError: list index out of range

**Comment by danielhb** [comment]
I believe this problem has to do with something else related to the Firmware feature because even here in my x86_64 system I can successfully (= without a 500 error) fetch the Firmware level:

```
[danielhb@arthas ginger]$ curl -k -u danielhb -H "Content-Type: application/json" -H "Accept: application/json" "http://localhost:8010/plugins/ginger/firmware" -X GET -d'{}'
Enter host password for user 'danielhb':
{
  "level":"Unknown"
}
```

Did you check the Capabilities API to see the status of the feature?  This API allows the user to poll the backend to check the status of its features. The reason for that is: Ginger runs in a wide range of machine setups and it would be an annoyance to make one distinct Ginger package for each different setup. For example, pSeries has exclusive features, the Power management feature depends on 'tuned' which isn't available in Ubuntu ...

The trick is that, in its current implementation, the API does not disable the 'blacklisted' backend models. If the UI or anyone using curl access the power management backend in Ubuntu, it will most likely  return a 500 server error because there is no tuned-adm binary.

This is an example of the capabilities API in an instance running in my local x86_64 with Fedora 22:

```
[danielhb@arthas ~]$ curl -u danielhb -H "Content-Type: application/json" -H "Accept: application/json" -k "https://localhost:8001/plugins/ginger/capabilities" -X GET 
Enter host password for user 'danielhb':
{
  "StorageDevs":true,
  "DASDPartitions":false,
  "PowerProfiles":false,
  "Swaps":true,
  "Sep":false,
  "LogicalVolumes":true,
  "SanAdapters":true,
  "VolumeGroups":true,
  "Firmware":false,
  "FileSystems":true,
  "PhysicalVolumes":true,
  "DASDdevs":false,
  "Users":true,
  "Sensors":false,
  "Partitions":true,
  "Backup":true,
  "Network":true
}
```

This does not prevent me from trying to get the 'ibm_sep' status of my machine for example. We can definitely improve this API by supplying better error messages for example - instead of a 500 error we would return "This feature is not available at this time".


Daniel

**Comment by lcorreia** [comment]
I see, it would be nice to have such error messages. But it is low priority.

**Comment by danielhb** [comment]
I agree. I'll mark this as Backlog and edit the issue title accordingly
