### ISSUE TITLE
GET operation /plugin/ginger/dasddevs/<bus id> fails with 500 status code

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#87]
Platform: s390x, OS: KVM for IBM z Systems
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugin/ginger/dasddevs/0.0.3b00'
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
} 

log: 
[22/Dec/2015:10:43:05] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 170, in index
    self.lookup()
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 146, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/dasddevs.py", line 64, in lookup
    self.dev_details = dasddevices[0]
IndexError: list index out of range

**Comment by harche** [comment]
I will be working on this issue

**Comment by harche** [comment]
`curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugin/ginger/dasddevs/NotAValidBusId'`

```
{
  "reason":"Nothing matches the given URI",
  "code":"404 Not Found"
}  
```         

As you can see above, I am not able to reproduce the issue. It's returning correct return code if you provide wrong bus ID.

**Comment by danielhb** [comment]
Fix was applied to remote master. Please let me know if it solved this issue

**Comment by harche** [comment]
@danielhb The fix works fine.

**Comment by danielhb** [comment]
Thanks!
