### ISSUE TITLE
GET on /plugins/ginger/filesystems/<mount point> fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#90]
Architecture: s390x, OS: KVM for IBM z Systems
The api fails with 500 when tried to retrieve filesystem details  with mount point which doesn't exist. Instead it should returning 404: Resource not found.

[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/filesystems/%2fcheck'
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}   

log:

[24/Dec/2015:08:12:34] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 171, in index
    if not self.is_authorized():
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 195, in is_authorized
    users = self.data.get("users", None)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/controls/filesystems.py", line 46, in data
    return {'filesystem': self.info['filesystem'],
KeyError: 'filesystem'

**Comment by sureshab** [comment]
For Create file system also it fails with 500 when /bin/mount command fails, instead it should be 400.

[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"local", "mount_point":"/test", "blk_dev":"/dev/dasdi"}' 'https://127.0.0.1:8001/plugins/ginger/filesystems'
{
  "reason":"GINFS00007E: Failed to mount the filesystem",
  "code":"500 Internal Server Error"
}

**Comment by ramonmedeiros** [comment]
Just sent a patch to the list

**Comment by danielhb** [comment]
Patch was applied upstream. Please check if the issue was fixed

**Comment by sureshab** [comment]
patch works fine.
